---
- hosts: master1
  become: yes
  vars:
    helm_version: v3.2.4
    helm_filename: helm-{{ helm_version }}-linux-amd64.tar.gz
    helm_url: https://get.helm.sh/{{ helm_filename }}
    helm_checksum: "sha256:8eb56cbb7d0da6b73cd8884c6607982d0be8087027b8ded01d6b2759a72e34b1"

  tasks:
  - name: Install helm
    block:
    - name: Get helm
      get_url:
        url: "{{ helm_url }}"
        dest: /tmp/
        checksum: "{{ helm_checksum }}"

    - name: unarchive helm
      unarchive:
        remote_src: yes
        src: /tmp/{{ helm_filename }}
        dest: /tmp

    - name: move helm binaries to PATH
      become: yes
      copy:
        remote_src: yes
        src: /tmp/linux-amd64/helm 
        dest: /usr/local/bin/helm
        mode: "0755"

    - name: remove temporary files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /tmp/{{ helm_filename }}
        - /tmp/linux-amd64
