---
- hosts: worker1 
  become: yes
  vars:
  - worker_ip: 192.168.50.12
  - user: vagrant

  tasks:
  - name: Ensure kubelet get the argument "node-ip"
    lineinfile:
      path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
      state: present
      line: Environment="KUBELET_EXTRA_ARGS=--node-ip={{ worker_ip }}"
    notify:
      - restart kubelet

  - name: create the data volume for prometheus-server
    file:
      path: /data/prometheus-data
      owner: "{{ user }}"
      state: directory

  handlers:
    - name: restart kubelet
      systemd: name=kubelet daemon_reload=yes enabled=yes state=restarted
