---
# for the first master
- hosts: master1
  become: yes
  vars:
  - master_ip: 192.168.50.11
  - user: ubuntu

  tasks:
  # - name: Reset Cluster
  #   command: "{{ item }}"
  #   with_items:
  #     - kubeadm reset -f
  #     - rm -fr /root/.kube

  - name: Initialize kubernetes cluster using the kubeadm config
    command: kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address {{ master_ip }}

  - name: Generate join command
    command: kubeadm token create --print-join-command
    register: join_command

  - name: copy join command to local file
    become: false
    local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"

  - name: Let regular user to control cluster
    block:
      - name: mkdir ~{{ user }}/.kube
        file:
          path: "~{{ user }}/.kube"
          state: directory

      - name: copy ssh keys
        copy:
          remote_src: yes
          src: /root/.ssh
          dest: "/home/{{ user }}/.ssh"

      - name: copy admin.conf
        copy:
          remote_src: yes
          src: /etc/kubernetes/admin.conf
          dest: "~{{ user }}/.kube/config"
          group: "{{ user }}"
          owner: "{{ user }}"

  - name: Install calico CNI
    command: kubectl apply -f https://docs.projectcalico.org/v3.15/manifests/calico.yaml
    remote_user: "{{ user }}"
    environment:
      KUBECONFIG: "/home/{{ user }}/.kube/config"
