---
- hosts: worker1
  become: yes
  tasks:
  # - name: Reset Cluster
  #   command: "{{ item }}"
  #   with_items:
  #     - kubeadm reset -f
  #     - rm -fr /root/.kube

  - name: Copy join-command to worker node
    copy:
      src: ./join-command
      dest: /tmp/join-command
      owner: root
      group: root
      mode: '0700'

  - name: Join cluster
    command: bash /tmp/join-command
