alertmanager:
  persistentVolume:
    enabled: false

server:
  persistentVolume:
    enabled: false

nodeExporter:
  tolerations:
    - key: "node-role.kubernetes.io/master"
      effect: "NoSchedule"
